import SignUpForm from "@/components/SignUpForm/SignUpForm";



export const metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

const SignInPage = () => {
  
  return (
    <div className="container mx-auto my-10">
      <SignUpForm></SignUpForm>
    </div>
  );
};

export default SignInPage;
